import type { Config } from 'tailwindcss';

const config: Config = {
	darkMode: ['class'],
	content: [
		'./pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./components/**/*.{js,ts,jsx,tsx,mdx}',
		'./app/**/*.{js,ts,jsx,tsx,mdx}',
		'*.{js,ts,jsx,tsx,mdx}',
	],
	safelist: [
		'mt-16',
		'md:mt-36',
		'mb-16',
		'md:mb-36',
		'my-16',
		'md:my-36',
		'ml-16',
		'md:ml-36',
		'mr-16',
		'md:mr-36',
		'mx-16',
		'md:mx-36',
		'md:mt-32',
		'md:mb-32',
		'md:my-32',
		'md:ml-32',
		'md:mr-32',
		'md:mx-32',
		'mt-12',
		'md:mt-16',
		'mb-12',
		'md:mb-16',
		'my-12',
		'md:my-16',
		'ml-12',
		'md:ml-16',
		'mr-12',
		'md:mr-16',
		'mx-12',
		'md:mx-16',
		'mt-6',
		'md:mt-8',
		'mb-6',
		'md:mb-8',
		'my-6',
		'md:my-8',
		'ml-6',
		'md:ml-8',
		'mr-6',
		'md:mr-8',
		'mx-6',
		'md:mx-8',
		'mt-4',
		'md:mt-4',
		'mb-4',
		'md:mb-4',
		'my-4',
		'md:my-4',
		'ml-4',
		'md:ml-4',
		'mr-4',
		'md:mr-4',
		'mx-4',
		'md:mx-4',
		'pt-16',
		'md:pt-32',
		'pb-16',
		'md:pb-32',
		'py-16',
		'md:py-32',
		'pl-16',
		'md:pl-32',
		'pr-16',
		'md:pr-32',
		'px-16',
		'md:px-32',
		'pt-12',
		'md:pt-16',
		'pb-12',
		'md:pb-16',
		'py-12',
		'md:py-16',
		'pl-12',
		'md:pl-16',
		'pr-12',
		'md:pr-16',
		'px-12',
		'md:px-16',
		'pt-6',
		'md:pt-8',
		'pb-6',
		'md:pb-8',
		'py-6',
		'md:py-8',
		'pl-6',
		'md:pl-8',
		'pr-6',
		'md:pr-8',
		'px-6',
		'md:px-8',
		'pt-4',
		'md:pt-4',
		'pb-4',
		'md:pb-4',
		'py-4',
		'md:py-4',
		'pl-4',
		'md:pl-4',
		'pr-4',
		'md:pr-4',
		'px-4',
		'md:px-4',
		'gap-16',
		'md:gap-32',
		'gap-12',
		'md:gap-16',
		'gap-6',
		'md:gap-8',
		'gap-4',
		'md:gap-4',
		'border-12',
		'border-14',
		'border-16',
		'border-18',
	],
	theme: {
		extend: {
			colors: {
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					'1': 'hsl(var(--chart-1))',
					'2': 'hsl(var(--chart-2))',
					'3': 'hsl(var(--chart-3))',
					'4': 'hsl(var(--chart-4))',
					'5': 'hsl(var(--chart-5))',
				},
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			keyframes: {
				'accordion-down': {
					from: {
						height: '0',
					},
					to: {
						height: 'var(--radix-accordion-content-height)',
					},
				},
				'accordion-up': {
					from: {
						height: 'var(--radix-accordion-content-height)',
					},
					to: {
						height: '0',
					},
				},
				'gradient-move': {
					'0%': { backgroundPosition: '0% 50%' },
					'100%': { backgroundPosition: '100% 50%' },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				'gradient-move': 'gradient-move 3s linear infinite',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
};
export default config;
