export const ROUTES = {
  HOME: "/",
  FEATURES_SAST: "/features/sast",
  FEATURES_SECRET_SCANNING: "/features/secret-scanning",
  FEATURES_SCA: "/features/sca",
  FEATURES_CONTAINER_SCANNING: "/features/container-scanning",
  FEATURES_CSPM: "/features/cspm",
  FEATURES_IAC: "/features/iac",
  FEATURES_DAST: "/features/dast",
  FEATURES_API_INVENTORY: "/features/api-inventory",
  FEATURES_API_AUTH_ANALYZER: "/features/api-auth-analyzer",
  FEATURES_AI_AUTOFIX: "/features/ai-autofix",
  FEATURES_CI_CD_SECURITY: "/features/ci-cd-security",
  FEATURES_OUTDATED_SOFTWARE_DETECTION: "/features/outdated-software-detection",
  FEATURES_WORKFLOW: "/features/workflow",
  BLOGS: "/blogs",
  BLOG_DETAIL: "/blogs/:slug",
  PRICING: "/pricing",
  RESOURCES: "/resources",
  ABOUT: "/about",
  CONTACT: "/contact",
  NOT_FOUND: "*",
};
